### ISSUE TITLE
[Dead-Hosts] Result of execution 

### ISSUE THREAD

**Issue by funilrys** [azet12/KADhosts#3]
Hello @azet12  ,

As you (may) know, I released and still continue to develop [Funceble](https://github.com/funilrys/funceble).

I wanted to help, so you can find here the result of my last execution against the following list.

[KADhosts@azet12](https://github.com/funilrys/dead-hosts/tree/master/KADhosts%40azet12)  ==> KADhosts :x:

Have a nice day/night.

Cheers,

## What does funceble do ?
It's a script that test if your host list are dead or not!

P.S: [referencement](https://github.com/StevenBlack/hosts/issues/259)

**Comment by azet12** [comment]
Hi! Sorry for delayed response.

This is really interesting, I will remove inactive pages soon.

**Comment by funilrys** [comment]
Hi there,
No problem it was just for information :) 
Gonna add a section with list of repo who use my script (result) you're gonna be there :wink:

**Comment by funilrys** [comment]
Hello @azet12  ,

You can find here the result of my last execution against the following list.

[KADhosts@azet12](https://github.com/funilrys/dead-hosts/tree/master/KADhosts%40azet12)  ==> KADhosts :x:

Have a nice day/night.

Cheers,

## What does funceble do ?
It's a script that test if your host list are dead or not!

P.S: [referencement](https://github.com/StevenBlack/hosts/issues/259)

**Comment by funilrys** [comment]
Hello @azet12  ,

You can find here the result of my last execution against the following list.

[KADhosts@azet12](https://github.com/funilrys/dead-hosts/tree/master/KADhosts%40azet12)  ==> KADhosts :x:

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      90%          2088        
INACTIVE    9%           208         
INVALID     0%           0           
```

Have a nice day/night.

Cheers,

## What is funceble?
To quote the most active user of Funceble:

> [Funceble is an] Excellent script for checking ACTIVE, INACTIVE and EXPIRED Domain Names.

**Comment by funilrys** [comment]
Hello @azet12,
I added a link to your repository into the following:

- https://github.com/funilrys/dead-hosts#valuable-links
- https://github.com/funilrys/funceble/tree/dev#valuable-links (Gonna be merged to master when I release a new version)

Cheers,
